version: '3.5'

services:
  backend:
    build: .
    image: proversjx/cropper
    command: gunicorn --bind 0.0.0.0:6000 wsgi:app
    container_name: python_backend_test1
    volumes:
      - /home/dev50/uploads/:/usr/src/app/uploads/
    ports:
      - 4567:6000
    env_file:
      - ./.env.dev