version: '3.7'

services:
  backend:
    build: .
    command: gunicorn --bind 0.0.0.0:6000 wsgi:app
    restart: always
    volumes:
      - /var/www/demonstration/data/www/pechat.photo/:/var/www/demonstration/data/www/pechat.photo/
      - /var/www/casycomua/data/www/casy.com.ua:/var/www/casycomua/data/www/casy.com.ua
      - /var/www/digitalfotoua/data/www/digitalfoto.pp.ua:/var/www/digitalfotoua/data/www/digitalfoto.pp.ua
      - /var/www/admin/data/www/gift-photo.com/:/var/www/admin/data/www/gift-photo.com/
      - /var/www/fotocarte/data/www/evolvestudio.md:/var/www/fotocarte/data/www/evolvestudio.md/
      - /var/www/foto124/data/www/foto124.ru:/var/www/foto124/data/www/foto124.ru/
      - /var/www/borovodessa/data/www/memory-moments.online:/var/www/borovodessa/data/www/memory-moments.online/
      - /var/www/photolier/data/www/online.photolier.ru:/var/www/photolier/data/www/online.photolier.ru/
      - /var/www/pechatfotoonline/data/www/pechatfotoonline.ru:/var/www/pechatfotoonline/data/www/pechatfotoonline.ru/
      - /var/www/photomich/data/www/photo-mich.ru:/var/www/photomich/data/www/photo-mich.ru/
      - /var/www/urakrasnodar/data/www/photopechat23.ru:/var/www/urakrasnodar/data/www/photopechat23.ru/
      - /var/www/admin/data/www/xn--80aj0aafqej6a4c.xn--80asehdb:/var/www/admin/data/www/xn--80aj0aafqej6a4c.xn--80asehdb/
      - /var/www/konigfoto/data/www/konigfoto.ru:/var/www/konigfoto/data/www/konigfoto.ru/
      - /var/www/antares/data/www/pixel-foto.ru:/var/www/antares/data/www/pixel-foto.ru/
      - /var/www/bpilot/data/www/100foto.ru:/var/www/bpilot/data/www/100foto.ru/
      - /var/www/2kadra/data/www/2kadra-foto.ru/:/var/www/2kadra/data/www/2kadra-foto.ru/
      - /var/www/suvenir38/data/www/xn--38-dlcmp3awds.xn--p1ai/:/var/www/suvenir38/data/www/xn--38-dlcmp3awds.xn--p1ai/
      - /var/www/fotoprintperm/data/www/fotoprintperm.ru/:/var/www/fotoprintperm/data/www/fotoprintperm.ru/
      - /var/www/printhouse64/data/www/printhouse64.com/:/var/www/printhouse64/data/www/printhouse64.com/
      - /var/www/alex/data/www/xn--h1aahfheaf3as4j.xn--p1ai/:/var/www/alex/data/www/xn--h1aahfheaf3as4j.xn--p1ai/
      - /var/www/tambov/data/www/xn--80aaaebe5avxvsy.xn--p1ai/:/var/www/tambov/data/www/xn--80aaaebe5avxvsy.xn--p1ai/
      - /var/www/goodpeople/data/www/xn---86-ndddrdwxav2d0bxf.xn--p1ai/:/var/www/goodpeople/data/www/xn---86-ndddrdwxav2d0bxf.xn--p1ai/
      - /var/www/korenovskcolorit/data/www/korenovskcolorit.ru/:/var/www/korenovskcolorit/data/www/korenovskcolorit.ru/
      - /var/www/fotoprint60/data/www/fotoprint60.ru/:/var/www/fotoprint60/data/www/fotoprint60.ru/
      - /var/www/ilshat/data/www/xn--24-plciib4bya.xn--p1ai/:/var/www/ilshat/data/www/xn--24-plciib4bya.xn--p1ai/
      - /var/www/fotokniga/data/www/foto-book.online/:/var/www/fotokniga/data/www/foto-book.online/
      - /var/www/birfotomir/data/www/birfotomir.ru/:/var/www/birfotomir/data/www/birfotomir.ru/
      - /var/www/fotodrug53/data/www/fotodrug53.ru/:/var/www/fotodrug53/data/www/fotodrug53.ru/
    ports:
      - 3350-3378:6000
    env_file:
      - ./.env.dev
